### ISSUE TITLE
申请支持php8

### ISSUE THREAD

**Issue by qu5** [idreamsoft/iCMS#104]
目前php8版本安装会报错，无法正常安装

> Warning: A non-numeric value encountered in /www/wwwroot/iPHP/function.php on line 426
> 
> Fatal error: Uncaught Error: Undefined constant "iPHP_DEBUG" in /www/wwwroot/iPHP/iPHP.php:74 Stack trace: #0 /www/wwwroot/iPHP/core/iDebug.php(131): iPHP::autoloadHandler() #1 /www/wwwroot/iPHP/core/iDebug.php(91): iDebug::errorPrint() #2 [internal function]: iDebug::exceptionHandler() #3 {main} thrown in /www/wwwroot/iPHP/iPHP.php on line 74
> 
> Fatal error: Uncaught Error: Undefined constant "iPHP_DEBUG" in /www/wwwroot/iPHP/iPHP.php:74 Stack trace: #0 /www/wwwroot/iPHP/core/iDebug.php(131): iPHP::autoloadHandler() #1 /www/wwwroot/iPHP/core/iDebug.php(106): iDebug::errorPrint() #2 [internal function]: iDebug::shutdownHandler() #3 {main} thrown in /www/wwwroot/iPHP/iPHP.php on line 74

**Comment by idreamsoft** [comment]
最新版本已经支持PHP8
