### ISSUE TITLE
安装完之后添加 几个分类  点击分类 是跳转到新的页面

### ISSUE THREAD

**Issue by linfeng** [idreamsoft/iCMS#13]
安装完之后添加 几个分类  点击分类 是跳转到新的页面
能否做到在当前页面做跳转不要用 _blank

**Comment by idreamsoft** [comment]
自己改模板

**Comment by linfeng** [comment]
怎样修改模版？有没有链接说明？或者例子

**Comment by idreamsoft** [comment]
https://www.icmsdev.com/docs/

**Comment by linfeng** [comment]
你好，我找好久，没找到，请您说明一下，想要管理后台那边怎样设置的？

**Comment by idreamsoft** [comment]
模板文件都在 /template/www 里自己找吧

**Comment by linfeng** [comment]
└── www [模板]
    ├── desktop [PC端模板]
    │   ├── article.htm [文章内容页]
    │   ├── **category.index.htm** [栏目首页]
    │   ├── **category.list.htm** [栏目列表页]

**Comment by linfeng** [comment]
category.index.htm  category.list.htm 我修改了这2个文件 并在后台更新缓存 还是没有生效

**Comment by linfeng** [comment]
里面都修改了 可以了
