### ISSUE TITLE
云存储不保存本地的设置下，上传文件返回错误

### ISSUE THREAD

**Issue by livepu** [idreamsoft/iCMS#23]
设置了云存储，不保存本地的情况下。上传文件，返回的是本地地址，而不是云地址。

**Comment by idreamsoft** [comment]
需要把附件地址改成云地址

暂时不能自适配

**Comment by livepu** [comment]
还有，这种纯粹云存储的方式，编辑器里面调用的图片，还是本地图片。这个明显不方便，应该调用云图片。

**Comment by idreamsoft** [comment]
@livepu 这么多云存储,暂时没想到有什么好办法部分替换掉,或者需要时替换
