### ISSUE TITLE
刷CVE的，不用在提交后台的CSRF,XSS了，谢谢！

### ISSUE THREAD

**Issue by idreamsoft** [idreamsoft/iCMS#36]
刷CVE的，不用在提交后台的CSRF,XSS了，谢谢！
后台有很多方面都没有你们安全人员考虑的仔细.所以问题比较多.
但是主要感觉后台都能进了,
在研究后台的csrf,XSS有点多此一举了
其它漏洞,还是很欢迎大家提交的

**Comment by twoHub** [comment]
还能拿这个刷CVE么  不提交这里提交哪里

**Comment by intAV** [comment]
前台csrf可以提交吗

**Comment by idreamsoft** [comment]
@intAV 可以

**Comment by intAV** [comment]
哈哈，什么时候放个大招呗，人家老是说提交csrf，没技术含量，来个前台getshell咋样

**Comment by idreamsoft** [comment]
@intAV 呵呵,那倒没这个意思.
后台很多方面也你们安全人员没考虑的仔细.所以问题比较多.
就是主要感觉后台都能进了,
在研究后台的csrf,XSS有点多此一举.

**Comment by TomAPU** [comment]
其实后台的CSRF还是有利用价值的啊

**Comment by idreamsoft** [comment]
@TomAPU 没什么用啊...多些一举而已.如果能进入后台,直接选备份数据库就可以了

**Comment by TerickJojo** [comment]
@idreamsoft 老哥，后台的CSRF是不需要进入后台就能执行攻击的。。。。

**Comment by idreamsoft** [comment]
@TerickJojo 了解 这个漏洞基本上都修复了 谢谢关注
