### ISSUE TITLE
 未经验证的session ，管理员退出登录状态之后session仍然有效

### ISSUE THREAD

**Issue by twoHub** [idreamsoft/iCMS#38]
This version is the latest v7.0.11.
Register a user first.
![1](https://user-images.githubusercontent.com/33438164/44082624-58316872-9fe4-11e8-8d09-0825b277f52a.png)
Then login the background management page, found in the member management office, you can login directly to any user.
![2](https://user-images.githubusercontent.com/33438164/44082768-c24f7afa-9fe4-11e8-91b6-e6ff438ba8a3.png)
Click on login, grab the packets, record the packets, and exit the background management page.
![default](https://user-images.githubusercontent.com/33438164/44082865-0c098e7e-9fe5-11e8-8988-63b9cbc13175.png)
![3](https://user-images.githubusercontent.com/33438164/44082892-20fbbc12-9fe5-11e8-8f7e-572a2de25e22.png)
After the exit stage is determined, the data packet is sent back and the user login is successful.
![4](https://user-images.githubusercontent.com/33438164/44083011-75cf95ba-9fe5-11e8-92f9-0471aec7080d.png)
![5](https://user-images.githubusercontent.com/33438164/44083028-80e9cfc4-9fe5-11e8-825f-eda5e1b12f02.png)
Then try the user with ID 1, and then change the ID to 1. in the packet.
The discovery is also successful, without the need for a password to login directly to the user, where seesion has not been verified.
![6](https://user-images.githubusercontent.com/33438164/44083214-ecf988a8-9fe5-11e8-9a0e-f91fbf104bef.png)
![7](https://user-images.githubusercontent.com/33438164/44083219-ee8a48b0-9fe5-11e8-95c7-6314c3605757.png)

**Comment by idreamsoft** [comment]
你这提交的要算什么？漏洞还是BUG？

**Comment by twoHub** [comment]
漏洞  你后台没有验证session  通过重放数据包可以登录任意用户

**Comment by idreamsoft** [comment]
数据包怎么得到的？

**Comment by twoHub** [comment]
我截图了  后台可以直接登陆用户  有个按钮

**Comment by idreamsoft** [comment]
这不是什么漏洞也不是BUG，本来的设计就是这样后台管理员可以登陆任意用户
就跟用户登陆是一样的操作，当然用户退出也要自己操作退出，
跟台后管理有没有登陆一点关系都没有
还是非常感谢您对本程序检测。
如有其它BUG或者漏洞欢迎提交。谢谢

**Comment by twoHub** [comment]
不是说你后台可以登录任意用户的问题  这个是主要原因是你的Cookie退出了还能再用

**Comment by idreamsoft** [comment]
哦  了解了，后台管理Cookie没有验证有效期，退出登陆是可以用同个Cookie继续访问。

**Comment by twoHub** [comment]
对的  这个算是问题吧。
