### ISSUE TITLE
账号退出时Cookie未完全失效

### ISSUE THREAD

**Issue by twoHub** [idreamsoft/iCMS#39]
![default](https://user-images.githubusercontent.com/33438164/44128730-0ce963c2-a077-11e8-899d-a9af66338af4.png)
正常登录的状态，然后抓取数据包
![default](https://user-images.githubusercontent.com/33438164/44128751-3247dcde-a077-11e8-8e9b-87b4d5ebb489.png)
把Cookie信息保存下来
Cookie: csrftoken=T7R480yQBIvZR8JZx0c6HXDcgEpaJ7fcKN4YYAeUoGfpnl7EKFdJhb40m5KUXANw; iCMS_article_category_tabs=list; iCMS_iCMS_AUTH=dbb61909tTDaB9qKdjWRqjyKY1UjkYN6jWrFWpOhjN1Dr1XWiZonf9Q3nb2WC5qOHkWI2petQQZmvpOb3Un4mdp74M0SVh7cJetO8PMCyOZKod1v9CHw

![default](https://user-images.githubusercontent.com/33438164/44128785-58206db8-a077-11e8-9c15-356e3bed924f.png)
这是退出登录后重新访问该页面，抓取数据包Cookie已经改变，然后替换成之前保留的cookie
![default](https://user-images.githubusercontent.com/33438164/44128819-8c88cb4a-a077-11e8-9ac3-09b415eb4699.png)
![default](https://user-images.githubusercontent.com/33438164/44128821-90440eca-a077-11e8-9a79-339a3a9ac086.png)
依然能登陆成功
![default](https://user-images.githubusercontent.com/33438164/44128852-cfd85dca-a077-11e8-97d6-1583d115a64a.png)
![default](https://user-images.githubusercontent.com/33438164/44128856-d5505ce4-a077-11e8-97f5-6e527c36f942.png)

——中科卓信软件测评技术中心

**Comment by idreamsoft** [comment]
这不是什么漏洞也不是BUG，本来的设计就是这样后台管理员可以登陆任意用户
就跟用户登陆是一样的操作，当然用户退出也要自己操作退出，
跟台后管理有没有登陆一点关系都没有
还是非常感谢您对本程序检测。
如有其它BUG或者漏洞欢迎提交。谢谢

**Comment by idreamsoft** [comment]
你这逻辑明显有问题，你用之前的正常登陆Cookie信息，重新访问面页是不是跟之前正常登陆没有区别!

Cookie信息有验证登陆IP，你在同个IP下用同个Cookie信息访问网站，系统都认为是同一个人
