### ISSUE TITLE
A vulnerability that can delete any folder in the server

### ISSUE THREAD

**Issue by ygang97** [idreamsoft/iCMS#46]
The `do_del () `method in `iCMS\app\database\database.admincp.php` does not filter the input content ,it can be used to delete any folder in the server.
![image](https://user-images.githubusercontent.com/36727917/50841944-bb533b80-13a0-11e9-9b65-fa4c59476ea4.png)
![image](https://user-images.githubusercontent.com/36727917/50841989-ce660b80-13a0-11e9-922b-e5c516d18d3f.png)

And there's also a small problem.
When deleting the backup file, only the backup folder is deleted, and the zip file is not deleted. The database file can be downloaded directly (It's hard to get the filename......).
![image](https://user-images.githubusercontent.com/36727917/50842012-dc1b9100-13a0-11e9-8fb9-12e69b8d075d.png)

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
