### ISSUE TITLE
注册用户发布文章时无法选择栏目

### ISSUE THREAD

**Issue by maysrp** [idreamsoft/iCMS#5]
栏目后台已经添加，但是注册用户无法选择栏目发布文章，而管理员则可以发布文章。
![sd.png](http://bilibara.com/images/2017/05/24/sd.png)

**Comment by idreamsoft** [comment]
https://www.icmsdev.com/docs/troubleshooting.html

在栏目配置里设置

**Comment by maysrp** [comment]
ok！！！
