### ISSUE TITLE
iCMS has a Front-end Storage XSS Vulnerability

### ISSUE THREAD

**Issue by yundiao** [idreamsoft/iCMS#60]
Testing environment：windows + firefox + apache2 + php5.4.45

**I . Vulnerability Analysis**
1.	When registering a new user, input mail address, the system will confirm whether it has been registered. Intercept the HTTP request.
Replace URI in BurpSuite as: 
/public/api.php?app=user&do=check&name=1&value=1&callback=confirm(document.cookie)&script=1
iCMS has global filtering. Filtered keywords such as alert and HTML tags. Using confirm instead of alert can bypass.
![register](https://user-images.githubusercontent.com/47202604/54937497-77afad00-4f5f-11e9-8d02-6f5780d97546.png)
![burpsuite](https://user-images.githubusercontent.com/47202604/54937569-9ca42000-4f5f-11e9-8526-68e1631f138d.png)

2.	Enter the  function API_check() of /app/user/user.app.php module. Then use iUI::json($a) to call function json() in /iPHP/core/iUI.class.php module.
Getting callback and script parameters by $_GET.
   But here is a reflect XSS, which needs to be converted to storage XSS.
![function-check](https://user-images.githubusercontent.com/47202604/54937654-c78e7400-4f5f-11e9-9446-18ad69622abd.png)
![function-json](https://user-images.githubusercontent.com/47202604/54937726-e8ef6000-4f5f-11e9-820f-5fe96b2f2d96.png)

**II.	Converted to storage XSS**

Setup http://localhost/install/index.php
Register a user at the front-end, then publish an article. Include the reflect XSS URL.
We need to add an article column in the background before publishing an article. This is what any user using the CMS will need to do.
![add](https://user-images.githubusercontent.com/47202604/54937780-0c1a0f80-4f60-11e9-88ce-38ebb83be883.png)
![addcategoryname](https://user-images.githubusercontent.com/47202604/54937850-323faf80-4f60-11e9-91b7-99f0cdfa3282.png)

We need to refresh the column before it can be displayed in the foreground.
![cache](https://user-images.githubusercontent.com/47202604/54937888-4c798d80-4f60-11e9-98c1-3e9c8a8e9342.png)

Front-end users publish an article.
![writearticle](https://user-images.githubusercontent.com/47202604/54937979-75018780-4f60-11e9-9ffe-4cb04fdeca4a.png)
![addlink](https://user-images.githubusercontent.com/47202604/54938045-96627380-4f60-11e9-9588-11a0fb806530.png)

Add hyperlinks to the text of the article.  Or we can insert a hyperlink after inserting a picture.
Fill in this link address:
http://127.0.0.1/public/api.php?app=user&do=check&name=1&value=1&callback=confirm(document.cookie)&script=1 

![inlink](https://user-images.githubusercontent.com/47202604/54938138-c7db3f00-4f60-11e9-8c09-52cad1d08a58.png)

It can be displayed after background auditing.
![checkarticle](https://user-images.githubusercontent.com/47202604/54938262-fc4efb00-4f60-11e9-8e38-c4064b4a7c82.png)
![checkarticlenow](https://user-images.githubusercontent.com/47202604/54938328-20124100-4f61-11e9-8f0b-d3b59181914d.png)
![clickme](https://user-images.githubusercontent.com/47202604/54938394-3e783c80-4f61-11e9-891a-92b938e28bb8.png)
![xxx](https://user-images.githubusercontent.com/47202604/54938428-4f28b280-4f61-11e9-9608-f10d3fb12f1a.png)

The last, converted to storage XSS.  Any visitor viewing this article will trigger the vulnerability.

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
