### ISSUE TITLE
There  are  two  SQL  inject  in  article.admincp.php   and  content.admincp.php  of  iCMS

### ISSUE THREAD

**Issue by yundiao** [idreamsoft/iCMS#61]
testing  environment:  windows7 + firefox + burpsuite + apache2 + php5.4.45 + mysql5.5

**I.	Vulnerability  Description**
The  function  do_updateorder()  in  /app/article/article.admincp.php  module  and  the  function 
do_updateorder()  in  /app/content/content.admincp.php.  The  same  SQL  injection  exists.
This  program  has  global  filtering.  But  only  the  parameter  values  are  filtered,  and  no  parameter Names  are  filtered. 
![function-do_updateorder](https://user-images.githubusercontent.com/47202604/54935753-ef7bd880-4f5b-11e9-8ffb-ed82fcaf950d.png)
![function-do_updateorder-content](https://user-images.githubusercontent.com/47202604/54935829-14704b80-4f5c-11e9-9914-aa38bfcad942.png)

Here,  the  parameter  name  also  brings  in  the  SQL  statement.  Although  the  parameter  values  are filtered  here  for  the  second  time.  However,  the  parameter  name  is  still  missing.
![function-update-article](https://user-images.githubusercontent.com/47202604/54935887-38339180-4f5c-11e9-9a8a-ff2a608a1185.png)
![function-update](https://user-images.githubusercontent.com/47202604/54935951-57322380-4f5c-11e9-94a4-87f9827c4df0.png)

So,  we  can  insert  an  error  based  SQL  statement  into  the  parameter  name  by  an  array. Implementing  SQL  Injection.

**II.	Vulnerability  testing**
Setup  iCMS:  http://127.0.0.1/install/index.php
This  vulnerability  needs  to  be  tested  in  the  manage  background.
Because  all  POST  requests  here  detect  CSRF-token.  The  entry  point  of  the  function  is  hard  to  find.  We  get  a  CSRF-token  value,  and  modify  the  HTTP  request  packages  to  enter  functions.
![CSRF_check](https://user-images.githubusercontent.com/47202604/54936071-a5dfbd80-4f5c-11e9-95c3-1bd2a130644b.png)

Get  a  CSRF-token  value:
After  landing  in  the  background,  enter  the  add  column.
![add_category](https://user-images.githubusercontent.com/47202604/54936190-e2131e00-4f5c-11e9-8080-ca83cbf948d0.png)

Open  BurpSuite  interception.  Write  a  column  name  and  submit  it.
![add_category_123456](https://user-images.githubusercontent.com/47202604/54936267-1ab2f780-4f5d-11e9-98a4-b396e5485cb6.png)

Burpsuite  modify  the  HTTP  package:
Modify URI to:
/admincp.php?app=article&do=updateorder  add  intercepted  & frame  and  & CSRF_TOKEN  parameters.
Modify  POST  DATA  to:
sortnum[3' and (extractvalue(1,concat(0x7e,(select database()),0x7e)))#]=1

Then  send  to  repeater.
![burpsuite_intercept](https://user-images.githubusercontent.com/47202604/54936383-51890d80-4f5d-11e9-8e65-7916b8cf19a1.png)

Get  database  name:
![repeater-database](https://user-images.githubusercontent.com/47202604/54936435-6cf41880-4f5d-11e9-93a9-ba050a655a57.png)

Get  user  name:
![repeater-user](https://user-images.githubusercontent.com/47202604/54936499-8bf2aa80-4f5d-11e9-9ef6-16bbf7b546a6.png)

Get  the  database  version:
![repeater-version](https://user-images.githubusercontent.com/47202604/54936650-e55ad980-4f5d-11e9-911d-de93ea91d79a.png)

The  same  SQL  injection  in  the  function  do_updateorder()  of  /app/content/content.admincp.php  module.
The  fixes  are  the  same.  Use  addslashes  to  filter  parameter  names.

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
