### ISSUE TITLE
Bug:V7.0.14 Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by Richard1266** [idreamsoft/iCMS#63]
There is an Stored Cross Site Scripting vulnerability in your latest version of the CMS v7.0.14
Download link: "https://patch.icmsdev.com/zip/releases/iCMS-v7.0.14.zip"
In the iCMSv7.0.14\app\article\article.admincp.php,not completely filtered to tags in the do_save() function:
![O2%GX@TBNL(`MWH{~ OHZGJ](https://user-images.githubusercontent.com/32863218/56192050-211a2800-6060-11e9-8b97-519242f4dfdc.png)
Vulnerability trigger point
http://localhost
1、Log in as admin
![1](https://user-images.githubusercontent.com/32863218/56192093-3c853300-6060-11e9-9767-1758d1565b77.png)
2、Add a section and add an article
![2](https://user-images.githubusercontent.com/32863218/56192167-6a6a7780-6060-11e9-9b46-6c10155b65fe.png)
![3](https://user-images.githubusercontent.com/32863218/56192180-6f2f2b80-6060-11e9-8be6-a7875aa70094.png)
![4](https://user-images.githubusercontent.com/32863218/56192187-735b4900-6060-11e9-89d3-94f60c1c250d.png)
![5](https://user-images.githubusercontent.com/32863218/56192192-77876680-6060-11e9-9d36-4b751657228e.png)
![8](https://user-images.githubusercontent.com/32863218/56192229-853cec00-6060-11e9-9a53-013cfcbaa605.png)
4、Refresh vulnerability trigger point
![7](https://user-images.githubusercontent.com/32863218/56192359-bc130200-6060-11e9-95d4-4386dd1eb402.png)
Fix:
Fully filter the tags parameter.

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
