### ISSUE TITLE
ICMS install Getshell

### ISSUE THREAD

**Issue by lyxhh** [idreamsoft/iCMS#66]
ICMS install Getshell

Vulnerability location：$db_name parameter in \icms-7.0.14 \install\install.php.

Cause :$db_name parameter is written directly to \iCMS-7.0.14\config.php without filtering
```
$db_name  = trim($_POST['DB_NAME']);
↓
define('iPHP_DB_NAME',$db_name);	
↓
$content = preg_replace("/define\('iPHP_DB_NAME',\s*'.*?'\)/is", 		"define('iPHP_DB_NAME','".iPHP_DB_NAME."')", $content);
↓
iFS::write($config_file,$content,false);
```

attack:
![image](https://user-images.githubusercontent.com/31927499/58793275-5d154680-8628-11e9-822f-eb5041eaadf5.png)

 
![image](https://user-images.githubusercontent.com/31927499/58793290-643c5480-8628-11e9-8fe3-7ea940008814.png)

Then request:
![image](https://user-images.githubusercontent.com/31927499/58793303-69010880-8628-11e9-9a31-b788ffb751e0.png)

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
