### ISSUE TITLE
Any file deletion + directory deletion + directory browsing

### ISSUE THREAD

**Issue by Leon2018hack** [idreamsoft/iCMS#69]
Set the file save directory to empty in the attachment settings and save it
![image](https://user-images.githubusercontent.com/44540678/61991729-41a64500-b087-11e9-91db-0196ae7c23b6.png)
Then choose to choose from the website by adding an article.
![image](https://user-images.githubusercontent.com/44540678/61991732-57b40580-b087-11e9-93e3-d94d9d91d6f6.png)
Click to choose from the website
![image](https://user-images.githubusercontent.com/44540678/61991736-64d0f480-b087-11e9-8de0-afb7e38d6323.png)
Directory browsing
![image](https://user-images.githubusercontent.com/44540678/61991741-731f1080-b087-11e9-8c9c-0c0217a6a2d8.png)
And can delete any file and any directory
![image](https://user-images.githubusercontent.com/44540678/61991751-829e5980-b087-11e9-96f1-a1c583059906.png)
![image](https://user-images.githubusercontent.com/44540678/61991752-8336f000-b087-11e9-8c08-0c6c3e36c90e.png)

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
