### ISSUE TITLE
“ URL设置 > 文件后缀设置不合法!”怎样取消

### ISSUE THREAD

**Issue by dvenwu** [idreamsoft/iCMS#7]
怎样取消这个限制以使用任意后缀作为后缀，例如我们想要使用.wifi

**Comment by idreamsoft** [comment]
无法取消
只允许使用正常的文件后缀
`			"png", "jpg", "jpeg", "gif", "bmp", "webp", "psd", "tif",
			"flv", "swf", "mkv", "avi", "rm", "rmvb", "mpeg", "mpg", "mp4",
			"ogg", "ogv", "mov", "wmv", "webm", "mp3", "wav", "mid", "amr",
			"rar", "zip", "tar", "gz", "7z", "bz2", "cab", "iso",
			"doc", "docx", "xls", "xlsx", "ppt", "pptx", "pdf", "txt", "md", "xml",
			"apk", "ipa",
			"html", "htm", "shtml",`

**Comment by dvenwu** [comment]
这个是在哪个文件里设定的呢

**Comment by dvenwu** [comment]
其实无所谓什么正常与不正常的后缀，只要nginx能够处理，这就不是问题，现在连新顶级域名，都已经放开

**Comment by idreamsoft** [comment]
可以自己修改源码 添加需要的后缀

位置:/iPHP/core/iFileSystem.class.php 514行

**Comment by dvenwu** [comment]
谢谢
