### ISSUE TITLE
iCMS V7.0.15 Stored XSS

### ISSUE THREAD

**Issue by YYHYlh** [idreamsoft/iCMS#72]
The vulnerability appears in the markdown editor at the editorial article. You can inject malicious code into the article by writing the xss payload in the markdonw editor. After that, whether the front-end user views the article or the background administrator previews the article, it will be affected by the XSS attack.

![image](https://user-images.githubusercontent.com/28374935/62990982-759fa980-be80-11e9-8be1-bbe79426d1e5.png)

The administrator previews in the background.

![image](https://user-images.githubusercontent.com/28374935/62991083-cc0ce800-be80-11e9-8bd3-8a13fc0fdc21.png)

General users view at the front desk.

![image](https://user-images.githubusercontent.com/28374935/62991133-fced1d00-be80-11e9-8fe9-4e833c7eb438.png)

**Comment by YYHYlh** [comment]
漏洞出现在编辑文章处的markdown编辑器。可以通过在markdonw编辑器里编写xss payload，将恶意代码注入到文章里，此后不管是前台用户查看文章或者后台管理员预览文章，都会受到XSS攻击的影响。

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
