### ISSUE TITLE
自定义表单提交出错

### ISSUE THREAD

**Issue by livepu** [idreamsoft/iCMS#75]
iPHP Error
Call to undefined method formsAdmincp::do_form_manage(1003) in iCMS://iPHP/iPHP.class.php on line 601

1. admincp::run() in iCMS://admincp.php on line 16
2. iPHP::error_throw() in iCMS://app/admincp/admincp.class.php on line 134
3. trigger_error() in iCMS://iPHP/iPHP.class.php on line 601
4. iPHP::error_handler()

应用场景是通过VG网页操作神器循环提交数据。返回访问：/admincp.php?app=forms&do=form_manage&fid=1
确实有init,就没有do_form_manage

**Comment by idreamsoft** [comment]
收到 会尽快修复的
