### ISSUE TITLE
DOS attack

### ISSUE THREAD

**Issue by forinfors** [idreamsoft/iCMS#83]
DOS attack exists in the comment module
![image](https://user-images.githubusercontent.com/54054880/66697558-3e773880-ed09-11e9-989e-de4577d6bce0.png)
Your review comment feature allows you to query up to 20 billion comments.
![image](https://user-images.githubusercontent.com/54054880/66697603-b34a7280-ed09-11e9-869a-0e28f9aa1970.png)
Attackers will cause your database to jam or crash through such an attack
![image](https://user-images.githubusercontent.com/54054880/66697627-0c1a0b00-ed0a-11e9-96a0-08cb9b3e715e.png)
Moreover, the query does not limit CSRF attacks, which can cause database crashes by constructing malicious links

**Comment by idreamsoft** [comment]
Thank you, we will fix it as soon as possible
