### ISSUE TITLE
A Stored XSS vulnerability exists in iCMS 7.0.15

### ISSUE THREAD

**Issue by NKingpp** [idreamsoft/iCMS#89]
**Notice**
I find a XSS vulnerability .It can execute JS code
**details**
It's in the system background ->application management -> system applications -> edit -> application introduction and app version
**payload**
<img src=1 onerror=alert(111)>
<img width="525" alt="1" src="https://user-images.githubusercontent.com/27681113/72049885-d978b200-32fa-11ea-8e63-b8ba4ac43615.png">
**Trigger**
Malicious code is triggered when an administrator accesses the app management page。
<img width="632" alt="2" src="https://user-images.githubusercontent.com/27681113/72050017-1c3a8a00-32fb-11ea-8d4a-64345fd1da89.png">
<img width="708" alt="3" src="https://user-images.githubusercontent.com/27681113/72050051-2f4d5a00-32fb-11ea-86f5-fbbaf3d1a393.png">

**Comment by idreamsoft** [comment]
收到 谢谢
