### ISSUE TITLE
A Stored XSS vulnerability exists in iCMS 7.0.15

### ISSUE THREAD

**Issue by NKingpp** [idreamsoft/iCMS#90]
**Notice**
I find a Stored XSS vulnerability .It can execute JS code。
**details**
It's in the system background ->Add application  ->application name 、Database table name、 Database  name and Template tags
<img width="714" alt="2" src="https://user-images.githubusercontent.com/27681113/72050779-e8f8fa80-32fc-11ea-8e9e-776b14076f31.png">

**Trigger**
Malicious code is triggered when an administrator accesses the app management page。
![1](https://user-images.githubusercontent.com/27681113/72050785-edbdae80-32fc-11ea-9ada-741cad6a9704.jpg)

**Comment by idreamsoft** [comment]
收到 谢谢
