### ISSUE TITLE
A sql injection  vulnerability exists in iCMS 7.0.15

### ISSUE THREAD

**Issue by NKingpp** [idreamsoft/iCMS#91]
The vulnerability lies in ICMs background database management module, database backup function. Click the backup table as shown in the figure below to send a post package. There is a table [] parameter in the post package. Use sqlmap to test this parameter to verify the SQL injection vulnerability.
 **post package**
You can get the post package on this function page through the tool
![1](https://user-images.githubusercontent.com/27681113/72498948-85764c00-386b-11ea-878d-99971bd28d13.png)
![2](https://user-images.githubusercontent.com/27681113/72498951-860ee280-386b-11ea-8dc1-718646514afa.png)

**Payload**
Parameter: table[] (POST)
    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: table[]=icms_user WHERE 9810=9810 AND (SELECT 4733 FROM (SELECT(SLEEP(5)))GXkw)-- hjiK&sizelimit=2048&batch=backup

**sqlmap**
![3](https://user-images.githubusercontent.com/27681113/72499000-ab9bec00-386b-11ea-9860-03c157f1cef9.png)

**Comment by idreamsoft** [comment]
收到 谢谢
